trigger:
  branches:
    include:
      - main

pool: default

variables:
  ServiceConnection: 'MyServiceConnection01'
  backendRG: 'MyRGc'
  backendST: 'myrgst5679807578jhj'
  backendCON: 'myrgccon'
  backendKEY: 'dev.terraform.tfstate'
  SubscriptionID: '89ce96dc-8535-4140-a60a-4ddca5655e3a'
  tfWorkingDir: '$(System.DefaultWorkingDirectory)/terraform'

stages:
- stage: Terraform
  jobs:
  - job: TerraformJob
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(tfWorkingDir)
        backendServiceArm: $(ServiceConnection)
        backendAzureRmOverrideSubscriptionID: $(SubscriptionID)
        backendAzureRmResourceGroupName: $(backendRG)
        backendAzureRmStorageAccountName: $(backendST)
        backendAzureRmContainerName: $(backendCON)
        backendAzureRmKey: $(backendKEY)

    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: $(tfWorkingDir)

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(tfWorkingDir)
        commandOptions: '-out=tfplan'
        environmentServiceNameAzureRM: $(ServiceConnection)
        environmentAzureRmOverrideSubscriptionID: $(SubscriptionID)

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: $(tfWorkingDir)
        commandOptions: 'tfplan --auto-approve'
        environmentServiceNameAzureRM: $(ServiceConnection)
        environmentAzureRmOverrideSubscriptionID: $(SubscriptionID)