trigger:
  branches:
    include:
      - main

pool: Default

variables:
  ServiceConnection: 'MyServiceConnection01'
  backendRG: 'MyRGc'
  backendST: 'myrgst5679807578jhj'
  backendCON: 'myrgccon'
  backendKEY: 'dev.terraform.tfstate'
  SubscriptionID: '0e01e4d0-ef71-4105-81fd-346e52ee7351'
  tfWorkingDir: '$(System.DefaultWorkingDirectory)'

stages:
- stage: Terraform
  jobs:
  - job: TerraformJob
    displayName: Terraform Installation & Deployment
    steps:

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: $(tfWorkingDir)
        backendServiceArm: $(ServiceConnection)
        backendAzureRmOverrideSubscriptionID: $(SubscriptionID)
        backendAzureRmResourceGroupName: $(backendRG)
        backendAzureRmStorageAccountName: $(backendST)
        backendAzureRmContainerName: $(backendCON)
        backendAzureRmKey: $(backendKEY)

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: $(tfWorkingDir)
        environmentServiceNameAzureRM: $(ServiceConnection)
        environmentAzureRmOverrideSubscriptionID: $(SubscriptionID)

    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: $(tfWorkingDir)
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: $(ServiceConnection)
        environmentAzureRmOverrideSubscriptionID: $(SubscriptionID)
